FROM node:20-alpine AS builder

WORKDIR /app

COPY ./frontend/package.json ./
COPY ./frontend/.npmrc ./
RUN npm install

COPY ./shared ../shared
COPY ./frontend/tsconfig.json ./
COPY ./frontend/tsconfig.node.json ./
COPY ./frontend/vite.config.ts ./
COPY ./frontend/index.html ./
COPY ./frontend/src ./src

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
